using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace KST.ScriptWizard {
    /// <summary>
    /// Generates a lua script from a WizardConfig.
    /// The generated script is purely declarative, all behavior lives in the lua libraries
    /// (keyspam.lua, mousespam.lua, holdbutton.lua, autorun.lua).
    /// </summary>
    internal static class ScriptGenerator {
        /// <summary>
        /// Marker for the embedded config, lets us re-open a generated script in the wizard.
        /// </summary>
        private const string ConfigMarker = "-- KST-WIZARD-CONFIG: ";

        private static readonly JsonSerializerSettings JsonSettings = new JsonSerializerSettings {
            NullValueHandling = NullValueHandling.Ignore,
            Culture = System.Globalization.CultureInfo.InvariantCulture,
            Converters = { new StringEnumConverter() }
        };

        /// <summary>
        /// Escapes a string for use inside a single quoted lua string.
        /// </summary>
        private static string Lua(string value) {
            if (value == null) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("'", "\\'");
        }

        /// <summary>
        /// Escapes a string for use inside a double quoted lua string.
        /// </summary>
        private static string LuaDq(string value) {
            if (value == null) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        /// <summary>
        /// The lua library each action depends on, and the prefix of its functions.
        /// CancelAll has no library, it is generated inline.
        /// </summary>
        private static string LibraryFor(WizardAction action) {
            switch (action) {
                case WizardAction.SpamKey: return "keyspam";
                case WizardAction.SpamMouseButton: return "mousespam";
                case WizardAction.HoldButton: return "holdbutton";
                case WizardAction.Autorun: return "autorun";
                default: return null;
            }
        }

        private static string PrefixFor(WizardAction action) {
            switch (action) {
                case WizardAction.SpamKey: return "ks";
                case WizardAction.SpamMouseButton: return "ms";
                case WizardAction.HoldButton: return "hb";
                case WizardAction.Autorun: return "ar";
                default: return null;
            }
        }

        public static string Generate(WizardConfig config) {
            var sb = new StringBuilder();

            // Libraries in a stable order, so regenerating an unchanged config yields an identical file.
            var libraries = config.Bindings
                .Select(m => LibraryFor(m.Action))
                .Where(m => m != null)
                .Distinct()
                .OrderBy(m => m, StringComparer.Ordinal)
                .ToList();

            var prefixes = config.Bindings
                .Select(m => PrefixFor(m.Action))
                .Where(m => m != null)
                .Distinct()
                .OrderBy(m => m, StringComparer.Ordinal)
                .ToList();

            var cancelBindings = config.Bindings.Where(m => m.Action == WizardAction.CancelAll).ToList();

            sb.AppendLine("-- Generated by the KST script wizard.");
            sb.AppendLine("-- Feel free to edit it by hand, but re-running the wizard will overwrite your changes.");
            sb.AppendLine(ConfigMarker + JsonConvert.SerializeObject(config, Formatting.None, JsonSettings));
            sb.AppendLine();

            sb.AppendLine("require \"core\"");
            foreach (var library in libraries) {
                sb.AppendLine($"require \"{library}\"");
            }
            sb.AppendLine();

            if (!string.IsNullOrEmpty(config.OutputPrefix)) {
                sb.AppendLine($"SetOutputPrefix(\"{LuaDq(config.OutputPrefix)}\")");
            }

            if (config.ColorMovementKeys) {
                sb.AppendLine();
                sb.AppendLine("-- Movement keys, purely cosmetic");
                sb.AppendLine("SetBacklightColor('W', 0, 100, 0)");
                sb.AppendLine("SetBacklightColor('S', 0, 100, 0)");
                sb.AppendLine("SetBacklightColor('A', 0, 0, 100)");
                sb.AppendLine("SetBacklightColor('D', 0, 0, 100)");
            }

            sb.AppendLine();
            sb.AppendLine("-- Key bindings. Active keys are green, inactive are red.");
            foreach (var binding in config.Bindings) {
                AppendBinding(sb, binding);
            }

            sb.AppendLine();
            AppendOutputHelpText(sb, config, prefixes, cancelBindings);

            sb.AppendLine();
            AppendReset(sb, prefixes, cancelBindings);

            sb.AppendLine();
            AppendOnEvent(sb, prefixes, cancelBindings);

            return sb.ToString();
        }

        private static void AppendBinding(StringBuilder sb, WizardBinding binding) {
            var trigger = Lua(binding.TriggerKey);
            var color = Lua(string.IsNullOrEmpty(binding.ColorKey) ? binding.TriggerKey : binding.ColorKey);
            var target = Lua(binding.Target);

            switch (binding.Action) {
                case WizardAction.SpamKey:
                    sb.AppendLine(binding.HoldToSpam
                        ? $"ks_add('{trigger}', '{color}', '{target}', true)"
                        : $"ks_add('{trigger}', '{color}', '{target}')");
                    break;

                case WizardAction.SpamMouseButton:
                    sb.AppendLine(binding.HoldToSpam
                        ? $"ms_add('{trigger}', '{color}', '{target}', true)"
                        : $"ms_add('{trigger}', '{color}', '{target}')");
                    break;

                case WizardAction.HoldButton:
                    sb.AppendLine($"hb_add('{trigger}', '{color}', '{target}')");
                    break;

                case WizardAction.Autorun:
                    var cancelKeys = string.Join(", ", (binding.CancelKeys ?? new List<string>())
                        .Where(m => !string.IsNullOrWhiteSpace(m))
                        .Select(m => $"'{Lua(m)}'"));
                    sb.AppendLine($"ar_add('{trigger}', '{color}', '{target}', {{{cancelKeys}}})");
                    break;

                case WizardAction.CancelAll:
                    sb.AppendLine($"SetBacklightColor('{color}', 0, 0, 100) -- {trigger}: cancel all scripts");
                    break;
            }
        }

        private static void AppendOutputHelpText(StringBuilder sb, WizardConfig config, List<string> prefixes, List<WizardBinding> cancelBindings) {
            sb.AppendLine("function OutputHelpText()");
            sb.AppendLine("\tOutputLogMessage('')");
            sb.AppendLine($"\tOutputLogMessage('{Lua(config.ScriptName)} mappings are:')");
            sb.AppendLine("\tOutputLogMessage('')");

            foreach (var prefix in prefixes) {
                sb.AppendLine($"\t{prefix}_outputHelpText()");
            }

            foreach (var binding in cancelBindings) {
                var color = Lua(string.IsNullOrEmpty(binding.ColorKey) ? binding.TriggerKey : binding.ColorKey);
                sb.AppendLine($"\tOutputLogMessage('- {color}: Cancel all scripts')");
            }

            sb.AppendLine("end");
        }

        private static void AppendReset(StringBuilder sb, List<string> prefixes, List<WizardBinding> cancelBindings) {
            sb.AppendLine("-- Stops every active script, also called when alt-tabbing out of the game.");
            sb.AppendLine("function reset()");

            if (prefixes.Count == 0) {
                sb.AppendLine("\t-- Nothing to reset");
            }

            foreach (var prefix in prefixes) {
                sb.AppendLine($"\t{prefix}_reset()");
            }

            sb.AppendLine("end");
        }

        private static void AppendOnEvent(StringBuilder sb, List<string> prefixes, List<WizardBinding> cancelBindings) {
            sb.AppendLine("function OnEvent(event, arg, modifiers)");
            sb.AppendLine("\tif event == FocusEvent then");
            sb.AppendLine("\t\tif arg == 'true' then");
            sb.AppendLine("\t\t\tOutputHelpText()");
            sb.AppendLine("\t\t\tRestoreColors()");
            sb.AppendLine("\t\telse");
            sb.AppendLine("\t\t\t-- Lost focus, stop everything so we don't keep holding keys down in another window.");
            sb.AppendLine("\t\t\treset()");
            sb.AppendLine("\t\tend");

            if (cancelBindings.Count > 0) {
                sb.AppendLine("\telseif event == KeyDownEvent then");
                var conditions = string.Join(" or ", cancelBindings.Select(m => $"arg == '{Lua(m.TriggerKey)}'"));
                sb.AppendLine($"\t\tif {conditions} then");
                sb.AppendLine("\t\t\tOutputLogMessage('Cancelling all scripts')");
                sb.AppendLine("\t\t\treset()");
                sb.AppendLine("\t\tend");
            }

            sb.AppendLine("\tend");

            if (prefixes.Count > 0) {
                sb.AppendLine();
                foreach (var prefix in prefixes) {
                    sb.AppendLine($"\t{prefix}_OnEvent(event, arg, modifiers)");
                }
            }

            sb.AppendLine("end");
        }

        /// <summary>
        /// Reads back the config embedded in a generated script.
        /// Returns null if the script was not generated by the wizard, or the header is unreadable.
        /// </summary>
        public static WizardConfig TryParseConfig(string script) {
            if (string.IsNullOrEmpty(script)) {
                return null;
            }

            foreach (var line in script.Split('\n')) {
                var trimmed = line.Trim();
                if (!trimmed.StartsWith(ConfigMarker, StringComparison.Ordinal)) {
                    continue;
                }

                try {
                    return JsonConvert.DeserializeObject<WizardConfig>(trimmed.Substring(ConfigMarker.Length), JsonSettings);
                }
                catch (JsonException) {
                    return null;
                }
            }

            return null;
        }
    }
}
